services:
  - type: web
    name: pocketbase-app
    env: docker
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO # Or omit if deploying from the linked Git repo
    plan: starter # Persistent disks require at least the Starter plan
    region: oregon # Choose your closest region
    envVars:
      - key: PORT
        value: 8080
    disk:
      name: pb-data-disk
      mountPath: /pb/pb_data
      sizeGB: 1
