services:
  - type: web
    name: pocketbase
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: pb-data
      mountPath: /pb/pb_data
      sizeGB: 1
    envVars:
      - key: PORT
        value: 8090
      - key: PB_ADMIN_EMAIL
        sync: false
      - key: PB_ADMIN_PASSWORD
        sync: false
